[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "mutagen>=1.48.1",
    "yt-dlp>=2026.3.17",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[project.scripts]
add-music = "scripts.add_music:main"
